config/routes.rb
Rails.application.routes.draw do


  resources :items
  
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help' 
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/items/new', to: 'items#new'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/users/verify' => "users#verify"
  post   '/items',    to: 'items#new'
  post  '/items/buy',  to: 'items#buy'
  post  '/users/profilefeed', to: 'users#profilefeed'
  post  '/items/purchase', to: 'items#purchase'
  post  '/static_pages/home', to: 'static_pages#home'
  post  '/static_pages/homefeed', to: 'static_pages#homefeed'
  get    '/search' => 'static_pages#search', :as => 'search_page'
  get   '/users/sendotp',  to:  'users#sendotp'
  get   '/users/OTPverifypage',  to:  'users#OTPverifypage'
  post  '/users/show', to: 'users#show'

  resources :users


  
end

app/views/shared/_error_messages.html.erb
<% if  object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>

	
	<ol class="container-fluid items">
	<%= render @feed_items %>
    </ol>
	<%= will_paginate @feed_items %>
<% else %>
 <h2>No items to show </h2>
<% end %>

app/views/shared/_filter.html.erb
<%= form_with(url: users_profilefeed_path, method: :post) do |f| %>
<%= f.select( :profile_feed_id, [["Unsold Items", 1],["Sold Items", 2],["Bought Items", 3]], { :selected => @profile_feed_id}, class: 'form-control' )%>

<%= f.submit "Filter", class: "btn btn-primary" %>
<% end %>

app/views/shared/_homefilter.html.erb
<%= form_with(url: static_pages_homefeed_path, method: :post) do |f| %>
<%= f.select( :home_feed_id,  Category.all.collect {|c| [ c.name, (c.id)] } << ["All", 0], { :selected => @home_feed_id || 0  }, class: 'form-control')%>

<%= f.submit "Filter", class: "btn btn-primary" %>
<% end %>

app/views/shared/_search.html.erb
<%= form_tag(search_page_path, :method => "get",   
    class: 'navbar-form navbar-left',  :style => 'width:100%;margin-top:20px;padding-left:0px;padding-right:0px;') do %>  
  <div class="input-group" style="width:100%">  
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control", value: @tag%>  
    <div class="input-group-btn search-button">  
      <%= button_tag "", :class => 'btn btn-primary glyphicon glyphicon-search',:name => nil%>  
    </div>  
  </div>  
<% end %>
</br>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 70), current_user %></br>
<h1 class="user-name"><%= current_user.name %></h1>
<span class="profile-link"><%= link_to "view my profile", current_user %></span>
</br>
</br>