config/routes.rb
Rails.application.routes.draw do


  resources :items
  
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help' 
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/items/new', to: 'items#new'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/users/verify' => "users#verify"
  post   '/items',    to: 'items#new'
  post  '/items/buy',  to: 'items#buy'
  post  '/users/profilefeed', to: 'users#profilefeed'
  post  '/items/purchase', to: 'items#purchase'
  post  '/static_pages/home', to: 'static_pages#home'
  post  '/static_pages/homefeed', to: 'static_pages#homefeed'
  get    '/search' => 'static_pages#search', :as => 'search_page'
  get   '/users/sendotp',  to:  'users#sendotp'
  get   '/users/OTPverifypage',  to:  'users#OTPverifypage'
  post  '/users/show', to: 'users#show'

  resources :users


  
end

app/models/item.rb
class Item < ApplicationRecord

  has_one :seller, class_name: "Seller", foreign_key: "item_id", dependent: :destroy
  has_one :buyer, class_name: "Buyer", foreign_key: "item_id", dependent: :destroy
  belongs_to :category
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :name, presence: true,  length: { maximum: 50 }
  validates :description, presence: true, length:{ maximum: 100}
  validates :price, numericality: { greater_than: 0 }


  private

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :edit]
  before_action :seller_user, only: [ :destroy, :edit]
  skip_before_action :verify_authenticity_token, only: [ :purchase ]

  def new
  	#@categories = Category.all.collect{ |u| [ u.name, u.id.to_i ] }
  	@item = Item.new
  end

  def index
  	@items = Item.all
  end

  def edit
  	if Item.exists?(id: params[:id]) 
  		@item = Item.find(params[:id])
  		if @item.sold == true
  			flash[:danger] = "Item sold out"
			redirect_to root_url
		end
  	else
    	flash[:danger] = "Item unavailable"
		redirect_to root_url
	end
  end

  def show
  	if Item.exists?(id: params[:id]) 
		@item = Item.find(params[:id])
	end	
  end

  def create
  	ver_params = item_params
  	ver_params[:category_id]  = item_params[:category_id].to_i
  	if ver_params[:category_id] == 0
  		@category_name = item_params[:category]
  		@verp = Hash.new
  		@verp[:name] = @category_name
  		@new_cat = Category.new(@verp)
  		if @new_cat.save
  			ver_params[:category_id] = @new_cat.id
  			@item = Item.new(ver_params.except(:category))
		  	if @item.save
		  		@seller = Seller.new
		  		@seller.update_attribute(:user_id, session[:user_id])
		  		@seller.update_attribute(:item_id, @item.id)
		  		if @seller.save
			  		flash[:success] = "Item created"
			        redirect_to root_url
			    else
			    	flash[:danger] = "Item not added to sellers table"
			    end
			end
		else
			flash[:danger] = "Category already exists"
  			render 'new'
	  	end
  	else
	  	@item = Item.new(ver_params.except(:category))
  		@seller = Seller.new
  		@seller.update_attribute(:user_id, session[:user_id])
  		@seller.update_attribute(:item_id, @item.id)
  		if @seller.save
	  		flash[:success] = "Item created"
	        redirect_to root_url
	    else
	    	flash[:danger] = "Item not added to sellers table"
	    end
	  
	end
  end

  def buy
  	@user = User.find(session[:user_id])
  	@id = params[:item_id]
  	if Item.exists?(id: @id)
	  	@item = Item.find(@id)
	  	if !@item.sold
		  	@buyer = Buyer.new
			@item.update_attribute(:sold, true)
		  	@buyer.update_attribute(:user_id, session[:user_id])
  			@buyer.update_attribute(:item_id, @item.id)
  			@buyer.save
		  	render 'purchase'
		 
		else
			flash[:danger] = "Item unavailable"
			redirect_to root_url
		end
	else
		flash[:danger] = "Item unavailable"
		redirect_to root_url
	end
	
  end


  def purchase
  	@itemid = params[:item_id]
  	@item = Item.find(@itemid)
	flash[:success] = "Item named #{@item.name} has been brought"
	redirect_to root_url
  end


  def update
  	@item = Item.find(params[:id])
  	ver_params = item_params
  	ver_params[:category_id]  = item_params[:category_id].to_i
  	if ver_params[:category_id] == 0
  		@category_name = item_params[:category]
  		@verp = Hash.new
  		@verp[:name] = @category_name
  		@new_cat = Category.new(@verp)
  		@new_cat.save
  		ver_params[:category_id] = @new_cat.id
  	end
  	if @item.update(ver_params.except(:category))
  	   flash[:success] = "Item Updated"
       redirect_to current_user
    else
    	render 'edit'
    end
  end

  def destroy
  	if Item.exists?(id: params[:id])
	  	@item = Item.find(params[:id])
	  	if @item.sold == true
  			flash[:danger] = "Item sold out"
			redirect_to root_url
		else
			@item.destroy
			flash[:success] = "Item deleted"
			redirect_to request.referrer || root_url
		end
	else
    	flash[:danger] = "Item unavailable"
		redirect_back_or root_url
	end
  end

  private

    def item_params
      params.require(:item).permit(:name, :category_id, :category, :price, :description, :picture)
    end

     # Confirms a logged-in user.
    def logged_in_user
      
      unless logged_in?

        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def seller_user
    	if Item.exists?(id: params[:id])
	    	@item = Item.find(params[:id])
	    	unless current_user?(@item.seller.user)
	    		store_location
	    		flash[:danger] = "Unauthorized content"
	        	redirect_to root_url
	        end
	    else
	    	flash[:danger] = "Item unavailable"
			redirect_back_or root_url
		end
    end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item.html.erb
<div>
<div id="item-<%= item.id %>" class="row" >
	<div  class="col-md-4 picture">
		<%= image_tag (item.picture.url if item.picture?) , :class => "img-thumbnail"%>
	</div>
	<div style="" class="col-md-4 info">
		<span class="name"><%= item.name %></span></br>
		<span class="price"><label>Price: &nbsp</label><span>&#8377</span><%= item.price %></span></br>
		<span class="category"><label>Category: &nbsp</label><%= item.category.name %></span></br>
		<% if item.description? %>
		<span class="description"><label>Description: &nbsp</label><%= item.description %></span>
		<% end %>
		<span class="timestamp">Posted <%= time_ago_in_words(item.created_at) %> ago.</span>
		<span class="links">
		<% if current_user?(item.seller.user) %>
			<% if !(item.sold) %>
			<%= link_to "Delete", item, method: :delete, data: { confirm: "You sure to delete?" } ,class: "btn btn-primary btn-sm"%>
			<span>&nbsp</span>
			<%= link_to "Edit", edit_item_path(item) , class: "btn btn-primary btn-sm"%>
			<% end %>
		<% else %>
			<% if !(item.sold) %>
			<%= link_to "Buy", items_buy_path(item_id: item.id), method: :post , class: "btn btn-primary btn-sm"%>
			<% end %>
			<span>&nbsp</span>
			<% @user = User.find(item.seller.user_id) %>
			<% @WHATS_LNK = "https://api.whatsapp.com/send?phone=#{@user.phone}&widget_hash=75698c0aa3b01bba00ffd5bc824aa29d&pre=1&text=I%20am%20interested%20in%20your%20product%20named%20#{item.name}%20which%20is%20posted%20#{time_ago_in_words(item.created_at)} ago." %>
			<button class='btn btn-primary btn-sm show_details'>Show Seller Details</button>
			<div class='details' style='display:none;margin:4px 0px 0px 10px;border-radius: 3px;padding:2px 0px 0px 8px'>
				<%= link_to image_tag("whatsapp.svg", alt: "whatsapp logo", width: "20"), @WHATS_LNK, target: "_blank" %><span>&nbsp</span><%= @user.phone %><span>&nbsp</span><span>&nbsp</span><span>&nbsp</span><span class="glyphicon glyphicon-envelope"></span><span>&nbsp</span><span>&nbsp</span><%= @user.email %><span style='display: inline;'>&nbsp</span><span>&nbsp</span><span>&nbsp</span>
			</div>
		<% end %>
	    </span>
	</div>

</div>
</div>

app/views/items/edit.html.erb
<% provide(:title, 'Edit Item') %>
<h1>Edit an Item</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= form_with(model: @item, local: true, html: { multipart: true }) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>

		<%= f.label :name %><p class='mandatory'style='display: inline;'>*</p> 
	    <%= f.text_field :name, class: 'form-control' , required: true%>

	    <%= f.label :category %><p class='mandatory'style='display: inline;'>*</p> 
	    <%= f.select( :category_id, Category.all.collect {|c| [ c.name, (c.id)] }, { :selected => @profile_feed_id}, class: 'form-control',:onchange => "newCategory(this);") %>

	    <div id='newCategoryDiv' style="display:none">
		    <%= f.text_field :category, class: 'form-control'%>
		</div>
		
	    <%= f.label :price %><p class='mandatory'style='display: inline;'>*</p> 
	    <%= f.number_field :price, value: number_to_currency(f.object.price.to_f, delimiter: '', unit: ''), step: :any, class: 'form-control' %>

		<%= f.label :description %><p class='mandatory'style='display: inline;'>*</p> 
		<%= f.text_area :description, placeholder: "Enter the description...", class: 'form-control', required: true%>

		<span class="picture">
			<%= f.file_field :picture , class: 'form-control', onchange: "validateFiles(this);", data: { max_file_size: 5.megabytes }%>
		</span>

		<%= f.submit "Update", class: "btn btn-primary" %>
	<% end %>
  </div>
</div>

app/views/items/index.html.erb
<% provide(:title, 'All Items') %>
<% if logged_in? && !current_user.verified %>
<div class="alert alert-danger">
	<strong>Pending Verification!</strong> The mobile number of this account hasn't been verified. Click <%= link_to "here", users_sendotp_path %> to verify your mobile number.
</div>
<% else %>
<div class="alert alert-warning">
	<strong>Nothing Here!</strong>  Click <%= link_to "here", root_url %> to redirect to home page.
</div>
<% end %>

app/views/items/new.html.erb
<% provide(:title, 'Add Item') %>

<%if current_user.verified %>
	<h1>Add an Item</h1>
	<div class="row">
	  <div class="col-md-6 col-md-offset-3">
		<%= form_with(model: @item, local: true, html: { multipart: true }) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %><p class='mandatory'style='display: inline;'>*</p>         
			<%= f.text_field :name, class: 'form-control',required: true%>

		    <%= f.label :category %><p class='mandatory'style='display: inline;'>*</p>
		    <%= f.select( :category_id, Category.all.collect {|c| [ c.name, (c.id)] }, { :selected => @profile_feed_id}, class: 'form-control',:onchange => "newCategory(this);") %>

		    <div id='newCategoryDiv' style="display:none">
		    <%= f.text_field :category, class: 'form-control'%>
			</div>

		    <%= f.label :price %><p class='mandatory'style='display: inline;'>*</p>
		    <%= f.number_field :price, value: number_to_currency(f.object.price.to_f, delimiter: '', unit: ''), step: :any ,required: true, class: 'form-control'%>

			<%= f.label :description %><p class='mandatory'style='display: inline;'>*</p>
			<%= f.text_area :description, placeholder: "Enter the description...",required: true, class: 'form-control'%>

			<span class="picture"><p class='mandatory'style='display: inline;'>*</p>
				<%= f.file_field :picture , accept: 'image/jpeg,image/gif,image/png',required: true, class: 'form-control', onchange: "validateFiles(this);", data: { max_file_size: 5.megabytes } %>
			</span>

			<%= f.submit "Post for sale", class: "btn btn-primary" %>
		<% end %>
	  </div>
	</div>
<% else %>
	<div class="alert alert-danger">
    <strong>Pending Verification!</strong> The mobile number of this account hasn't been verified. Click <%= link_to "here", users_sendotp_path %> to verify your mobile number.
    </div>
<% end %>

app/views/items/purchase.html.erb
<div>
    <div class="loadmeRect">
        <div class="loadmeRectChild loadmeRect1"></div>
        <div class="loadmeRectChild loadmeRect2"></div>
        <div class="loadmeRectChild loadmeRect3"></div>
        <div class="loadmeRectChild loadmeRect4"></div>
        <div class="loadmeRectChild loadmeRect5"></div>
    </div>
    <div class="loadme-mask"></div>
</div>

<div class='instructions' id='text' style='margin-top:40px;font:normal normal bold 35px/90px Georgia, serif;text-align: center;vertical-align: middle;line-height: 90px;'> 

</div>

<%= javascript_tag do %>
     Item.getConnectionActivityStats("<%= items_purchase_path.html_safe %>", <%= @item.id %>);
<% end %>

app/views/items/show.html.erb
<% if logged_in? && !current_user.verified %>
<div class="alert alert-danger">
	<strong>Pending Verification!</strong> The mobile number of this account hasn't been verified. Click <%= link_to "here", users_sendotp_path %> to verify your mobile number.
</div>
<% else %>
<div class="alert alert-warning">
	<strong>Nothing Here!</strong>  Click <%= link_to "here", root_url %> to redirect to home page.
</div>
<% end %>