config/routes.rb
Rails.application.routes.draw do


  resources :items
  
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help' 
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/items/new', to: 'items#new'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/users/verify' => "users#verify"
  post   '/items',    to: 'items#new'
  post  '/items/buy',  to: 'items#buy'
  post  '/users/profilefeed', to: 'users#profilefeed'
  post  '/items/purchase', to: 'items#purchase'
  post  '/static_pages/home', to: 'static_pages#home'
  post  '/static_pages/homefeed', to: 'static_pages#homefeed'
  get    '/search' => 'static_pages#search', :as => 'search_page'
  get   '/users/sendotp',  to:  'users#sendotp'
  get   '/users/OTPverifypage',  to:  'users#OTPverifypage'
  post  '/users/show', to: 'users#show'

  resources :users


  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
 
</footer>

app/views/layouts/_header.html.erb
<% @user = User.find_by(id: session[:user_id]) %>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Sell & Buy", root_path, id: "logo" %>
    <nav >
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <%if logged_in? %><li><%= link_to "Add Item", items_new_path %></li><% end %>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @user.name %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "View Profile", current_user %></li>
              <li><%= link_to "Update Profile", edit_user_path(current_user) %></li>
              <% if !( (session[:user_id] == nil) || @user.verified) %>
              <li >
                <%= link_to "Verify Mobile", users_sendotp_path  %>
              </li>
              <% end %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  	<head>
	   <title><%= full_title(yield(:title)) %></title>
	   <meta charset="utf-8">
	   <%= csrf_meta_tags %>
		<%= stylesheet_link_tag 'application', media: 'all',
		'data-turbolinkstrack': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinkstrack': 'reload' %>
	 <%= render 'layouts/shim' %>
  	</head>
  <body>
    	<%= render 'layouts/header' %> 	
	   	
	  	<div class="container">
	  		<% flash.each do |message_type, message| %>
        		<div class="alert alert-<%= message_type %>"><%= message %></div>
      		<% end %>
	    	<%= yield %>
	    	
	  	</div>
  </body>
</html>